bilangan = 9
print('bilangan = ',bilangan)
bilangan += 2
print('bilangan + 2 =',bilangan )
bilangan -= 2
print('bilanhan - 2 =',bilangan)
bilangan += 2
print('bilangan + 2=',bilangan)
bilangan /= 2
print('dibagi 2 =',bilangan)
bilangan //=2
print('hasil bagi dengan 2 =',bilangan)
bilangan %=2
print('sisa hasil dengan 2=',bilangan)
bilangan **=2
print('dipangkat 2 =',bilangan)
